name: SPC-Workflow

on: 
  push: 
    branches:
      - main 

jobs:
  build: 
    name: spring-petclinic
    runs-on: self-hosted 

    steps: 
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Build java with maven 
        run: mvn package